name: "build"

on: [pull_request, push, workflow_dispatch]

env:
  VERSION: "0.1.0"

jobs:
  build-mac:
    name: 'Build for macOS'
    runs-on: ${{ matrix.job.on }}
    strategy:
      matrix:
        job:
          - {
              target: 'aarch64-apple-darwin',
              on: 'macos-latest',
              arch: 'aarch64',
            }
          - {
              target: 'x86_64-apple-darwin',
              on: 'macos-latest',
              arch: 'x64',
            }
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.job.target }}

      - name: install frontend dependencies
        run: npm install

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: '--target ${{ matrix.job.target }}'

      - name: determine artifact names
        run: |
          echo "DMG_NAME=Volkanic Console_${{ env.VERSION }}_${{ matrix.job.arch }}.dmg" >> $GITHUB_ENV
          echo "DMG_PATH=src-tauri/target/${{ matrix.job.target }}/release/bundle/dmg/Volkanic Console_${{ env.VERSION }}_${{ matrix.job.arch }}.dmg" >> $GITHUB_ENV

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.DMG_NAME }}
          path: ${{ env.DMG_PATH }}
